name: Execucao da Analise de Campanhas

on:
  # O único gatilho agora é o manual/externo, que o Google vai usar
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar o Script de Análise
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MELI_CLIENTS_CSV: ${{ secrets.MELI_CLIENTS_CSV }}
        run: python daily_run.py