name: Execucao Periodica de Atualizacao de Dados

on:
  # Mantém o gatilho manual para que você possa executar a qualquer momento.
  workflow_dispatch:

  # Adiciona o agendamento para 4 execuções diárias.
  schedule:
    # Horários em UTC (3 horas à frente do fuso de Brasília - BRT)
    # 09:00 BRT -> 12:00 UTC
    - cron: '0 12 * * *'
    # 11:30 BRT -> 16:00 UTC
    - cron: '30 14 * * *'
    # 17:00 BRT -> 20:00 UTC
    - cron: '0 20 * * *'
    # 21:00 BRT -> 00:00 UTC (do dia seguinte)
    - cron: '0 0 * * *'

jobs:
  run-realtime-update:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar o Script de Atualização em Tempo Real
        env:
          # As credenciais são lidas a partir dos Segredos do seu repositório no GitHub.
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MELI_CLIENTS_CSV: ${{ secrets.MELI_CLIENTS_CSV }}
        # Garante que o script correto seja executado.
        run: python realtime_update.py