name: Execucao Diaria da Analise de Campanhas

on:
  workflow_dispatch: # Permite iniciar manualmente pela interface do GitHub
  schedule:
    # ATUALIZADO: Roda todos os dias às 02:30 UTC (23:30 no horário de Brasília)
    - cron: '49 2 * * *'

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar o Script de Análise
        env:
          # Passa os segredos do GitHub para o script como variáveis de ambiente
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MELI_CLIENTS_CSV: ${{ secrets.MELI_CLIENTS_CSV }}
        run: python daily_run.py